package com.memento.app.ui.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color
import com.memento.app.data.preferences.ThemePalette

@Immutable
data class PalettePreviewColors(
    val primary: Color,
    val secondary: Color,
    val surface: Color,
)

fun ThemePalette.previewColors(dark: Boolean): PalettePreviewColors {
    val scheme = colorSchemeFor(this, dark)
    return PalettePreviewColors(scheme.primary, scheme.secondary, scheme.surfaceVariant)
}

fun colorSchemeFor(palette: ThemePalette, dark: Boolean): ColorScheme = when (palette) {
    ThemePalette.MEMENTO -> if (dark) MementoDarkColors else MementoLightColors
    ThemePalette.FOREST -> if (dark) ForestDarkColors else ForestLightColors
    ThemePalette.NOBLE -> if (dark) NobleDarkColors else NobleLightColors
    ThemePalette.INK -> if (dark) InkDarkColors else InkLightColors
}

private val MementoLightColors = lightColorScheme(
    primary = Color(0xFF745166),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFF3DDE8),
    onPrimaryContainer = Color(0xFF2C1724),
    secondary = Color(0xFF765A43),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFF2DFCE),
    onSecondaryContainer = Color(0xFF2D1B0F),
    tertiary = Color(0xFF665E2E),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFEEE7A8),
    onTertiaryContainer = Color(0xFF211F00),
    background = Color(0xFFFFF8F5),
    onBackground = Color(0xFF241F21),
    surface = Color(0xFFFFF8F5),
    onSurface = Color(0xFF241F21),
    surfaceDim = Color(0xFFE1D9DC),
    surfaceBright = Color(0xFFFFF8F5),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFFAF1F4),
    surfaceContainer = Color(0xFFF4EBEE),
    surfaceContainerHigh = Color(0xFFEEE5E8),
    surfaceContainerHighest = Color(0xFFE8DFE2),
    surfaceVariant = Color(0xFFF0E5E5),
    onSurfaceVariant = Color(0xFF50464B),
    outline = Color(0xFF82747A),
    outlineVariant = Color(0xFFD4C3C9),
    inverseSurface = Color(0xFF392E32),
    inverseOnSurface = Color(0xFFFFEFF3),
    inversePrimary = Color(0xFFE2B8CF),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    scrim = Color(0xFF000000),
)

private val MementoDarkColors = darkColorScheme(
    primary = Color(0xFFE2B8CF),
    onPrimary = Color(0xFF422536),
    primaryContainer = Color(0xFF5A3B4D),
    onPrimaryContainer = Color(0xFFFED8EB),
    secondary = Color(0xFFDDBD9F),
    onSecondary = Color(0xFF3E2D20),
    secondaryContainer = Color(0xFF58432F),
    onSecondaryContainer = Color(0xFFFADDC1),
    tertiary = Color(0xFFD4CA7D),
    onTertiary = Color(0xFF383100),
    tertiaryContainer = Color(0xFF504800),
    onTertiaryContainer = Color(0xFFF1E694),
    background = Color(0xFF1B1719),
    onBackground = Color(0xFFEDE0E4),
    surface = Color(0xFF1B1719),
    onSurface = Color(0xFFEDE0E4),
    surfaceDim = Color(0xFF1B1719),
    surfaceBright = Color(0xFF42383C),
    surfaceContainerLowest = Color(0xFF151113),
    surfaceContainerLow = Color(0xFF241F21),
    surfaceContainer = Color(0xFF292426),
    surfaceContainerHigh = Color(0xFF342E31),
    surfaceContainerHighest = Color(0xFF40393C),
    surfaceVariant = Color(0xFF332D30),
    onSurfaceVariant = Color(0xFFD4C3C9),
    outline = Color(0xFF9D8D93),
    outlineVariant = Color(0xFF50464B),
    inverseSurface = Color(0xFFEDE0E4),
    inverseOnSurface = Color(0xFF392E32),
    inversePrimary = Color(0xFF745166),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    scrim = Color(0xFF000000),
)

private val ForestLightColors = lightColorScheme(
    primary = Color(0xFF3F6650),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFD4E8D9),
    onPrimaryContainer = Color(0xFF102A1B),
    secondary = Color(0xFF6B6046),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFEFE3C4),
    onSecondaryContainer = Color(0xFF241F0B),
    tertiary = Color(0xFF52646D),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFD5E8F0),
    onTertiaryContainer = Color(0xFF101F25),
    background = Color(0xFFFAF8F1),
    onBackground = Color(0xFF1B1C19),
    surface = Color(0xFFFAF8F1),
    onSurface = Color(0xFF1B1C19),
    surfaceDim = Color(0xFFDAD9D2),
    surfaceBright = Color(0xFFFAF8F1),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFF4F2EB),
    surfaceContainer = Color(0xFFEEEDE6),
    surfaceContainerHigh = Color(0xFFE8E7E0),
    surfaceContainerHighest = Color(0xFFE2E1DA),
    surfaceVariant = Color(0xFFE7ECE4),
    onSurfaceVariant = Color(0xFF424943),
    outline = Color(0xFF737A73),
    outlineVariant = Color(0xFFC3CBC3),
    inverseSurface = Color(0xFF30312E),
    inverseOnSurface = Color(0xFFF2F1EA),
    inversePrimary = Color(0xFFA6D0B2),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    scrim = Color(0xFF000000),
)

private val ForestDarkColors = darkColorScheme(
    primary = Color(0xFFA6D0B2),
    onPrimary = Color(0xFF113720),
    primaryContainer = Color(0xFF284B38),
    onPrimaryContainer = Color(0xFFC1EDD0),
    secondary = Color(0xFFD5C4A1),
    onSecondary = Color(0xFF3A2F18),
    secondaryContainer = Color(0xFF51472F),
    onSecondaryContainer = Color(0xFFF1E0BB),
    tertiary = Color(0xFFB9CAD1),
    onTertiary = Color(0xFF23343A),
    tertiaryContainer = Color(0xFF3A4B52),
    onTertiaryContainer = Color(0xFFD5E7EE),
    background = Color(0xFF151A16),
    onBackground = Color(0xFFE3EAE3),
    surface = Color(0xFF151A16),
    onSurface = Color(0xFFE3EAE3),
    surfaceDim = Color(0xFF151A16),
    surfaceBright = Color(0xFF3B413C),
    surfaceContainerLowest = Color(0xFF101511),
    surfaceContainerLow = Color(0xFF1E231F),
    surfaceContainer = Color(0xFF232824),
    surfaceContainerHigh = Color(0xFF2E332F),
    surfaceContainerHighest = Color(0xFF393E3A),
    surfaceVariant = Color(0xFF29302A),
    onSurfaceVariant = Color(0xFFC3CBC3),
    outline = Color(0xFF8D968E),
    outlineVariant = Color(0xFF424943),
    inverseSurface = Color(0xFFE3EAE3),
    inverseOnSurface = Color(0xFF303530),
    inversePrimary = Color(0xFF3F6650),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    scrim = Color(0xFF000000),
)

private val NobleLightColors = lightColorScheme(
    primary = Color(0xFF405C86),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFD8E2F5),
    onPrimaryContainer = Color(0xFF102644),
    secondary = Color(0xFF75643F),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFF0E2BD),
    onSecondaryContainer = Color(0xFF271D05),
    tertiary = Color(0xFF65587A),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFEBDDFF),
    onTertiaryContainer = Color(0xFF211632),
    background = Color(0xFFFAF8F3),
    onBackground = Color(0xFF1A1C20),
    surface = Color(0xFFFAF8F3),
    onSurface = Color(0xFF1A1C20),
    surfaceDim = Color(0xFFDADAE0),
    surfaceBright = Color(0xFFFAF8F3),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFF4F2F6),
    surfaceContainer = Color(0xFFEEEFF4),
    surfaceContainerHigh = Color(0xFFE8E9EF),
    surfaceContainerHighest = Color(0xFFE2E3E9),
    surfaceVariant = Color(0xFFE5E8EF),
    onSurfaceVariant = Color(0xFF44474D),
    outline = Color(0xFF75777E),
    outlineVariant = Color(0xFFC5C6CD),
    inverseSurface = Color(0xFF2F3035),
    inverseOnSurface = Color(0xFFF1F0F5),
    inversePrimary = Color(0xFFAEC7F0),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    scrim = Color(0xFF000000),
)

private val NobleDarkColors = darkColorScheme(
    primary = Color(0xFFAEC7F0),
    onPrimary = Color(0xFF17304F),
    primaryContainer = Color(0xFF294568),
    onPrimaryContainer = Color(0xFFD8E2F5),
    secondary = Color(0xFFD9C18A),
    onSecondary = Color(0xFF3D2F0A),
    secondaryContainer = Color(0xFF554619),
    onSecondaryContainer = Color(0xFFF6DEA5),
    tertiary = Color(0xFFCEBFE5),
    onTertiary = Color(0xFF362947),
    tertiaryContainer = Color(0xFF4D405F),
    onTertiaryContainer = Color(0xFFEBDDFF),
    background = Color(0xFF141820),
    onBackground = Color(0xFFE4E7EE),
    surface = Color(0xFF141820),
    onSurface = Color(0xFFE4E7EE),
    surfaceDim = Color(0xFF141820),
    surfaceBright = Color(0xFF3A3E47),
    surfaceContainerLowest = Color(0xFF0F131B),
    surfaceContainerLow = Color(0xFF1D2129),
    surfaceContainer = Color(0xFF22262F),
    surfaceContainerHigh = Color(0xFF2D313A),
    surfaceContainerHighest = Color(0xFF383C45),
    surfaceVariant = Color(0xFF292E37),
    onSurfaceVariant = Color(0xFFC5C6CD),
    outline = Color(0xFF8F9199),
    outlineVariant = Color(0xFF44474D),
    inverseSurface = Color(0xFFE4E7EE),
    inverseOnSurface = Color(0xFF2F3035),
    inversePrimary = Color(0xFF405C86),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    scrim = Color(0xFF000000),
)

private val InkLightColors = lightColorScheme(
    primary = Color(0xFF344A64),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFDDE8F2),
    onPrimaryContainer = Color(0xFF0C1D2D),
    secondary = Color(0xFF655F58),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFEAE2DA),
    onSecondaryContainer = Color(0xFF221F1B),
    tertiary = Color(0xFF4E6068),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFD1E9F1),
    onTertiaryContainer = Color(0xFF0B1E24),
    background = Color(0xFFFBFAF7),
    onBackground = Color(0xFF1B1C1D),
    surface = Color(0xFFFBFAF7),
    onSurface = Color(0xFF1B1C1D),
    surfaceDim = Color(0xFFDCDAD6),
    surfaceBright = Color(0xFFFBFAF7),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFF5F4F1),
    surfaceContainer = Color(0xFFEFEDEA),
    surfaceContainerHigh = Color(0xFFE9E7E4),
    surfaceContainerHighest = Color(0xFFE3E1DE),
    surfaceVariant = Color(0xFFE9E8E4),
    onSurfaceVariant = Color(0xFF464746),
    outline = Color(0xFF777876),
    outlineVariant = Color(0xFFC7C7C3),
    inverseSurface = Color(0xFF303031),
    inverseOnSurface = Color(0xFFF2F1EE),
    inversePrimary = Color(0xFFB8C9DD),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    scrim = Color(0xFF000000),
)

private val InkDarkColors = darkColorScheme(
    primary = Color(0xFFB8C9DD),
    onPrimary = Color(0xFF203448),
    primaryContainer = Color(0xFF30465D),
    onPrimaryContainer = Color(0xFFDDE8F2),
    secondary = Color(0xFFCCC5BA),
    onSecondary = Color(0xFF34302B),
    secondaryContainer = Color(0xFF4B4640),
    onSecondaryContainer = Color(0xFFE9E2D8),
    tertiary = Color(0xFFB6CAD2),
    onTertiary = Color(0xFF20343A),
    tertiaryContainer = Color(0xFF374B52),
    onTertiaryContainer = Color(0xFFD1E9F1),
    background = Color(0xFF151719),
    onBackground = Color(0xFFE5E2DF),
    surface = Color(0xFF151719),
    onSurface = Color(0xFFE5E2DF),
    surfaceDim = Color(0xFF151719),
    surfaceBright = Color(0xFF3B3D3F),
    surfaceContainerLowest = Color(0xFF101214),
    surfaceContainerLow = Color(0xFF1E2022),
    surfaceContainer = Color(0xFF232527),
    surfaceContainerHigh = Color(0xFF2E3032),
    surfaceContainerHighest = Color(0xFF393B3D),
    surfaceVariant = Color(0xFF2C2F32),
    onSurfaceVariant = Color(0xFFC7C7C3),
    outline = Color(0xFF91918E),
    outlineVariant = Color(0xFF464746),
    inverseSurface = Color(0xFFE5E2DF),
    inverseOnSurface = Color(0xFF303031),
    inversePrimary = Color(0xFF344A64),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    scrim = Color(0xFF000000),
)
